version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - CLIENT_URL=http://localhost:3000
      - NODE_ENV=test
  frontend:
    build:
      context: .
      dockerfile: client.Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8001
        - NEXT_PUBLIC_INTERNAL_API_URL=http://server:8001
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - server
