name: Run playbook
on: [push]
jobs:
  Deploy-Playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject Python dependencies into Ansible
        run: pipx inject ansible-core docker requests

      - name: Run Ansible Playbook to Deploy
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: infra/deploy-playbook.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [oracle]
            ${{ secrets.SSH_HOST }} ansible_user=${{ secrets.SSH_USERNAME }}
          options: |
            --extra-vars "vm_public_ip=${{ secrets.SSH_HOST }} db_password=${{ secrets.PROD_DB_PASSWORD }}"
